name: CD using ArgoCD
on:
  push:
    branches: [main]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: create namespace for argocd
      run: |
        kubectl create ns argocd
    - name: install argocd
      run: |
        kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    - name: verify ArgoCD installation
      run: |
        kubectl get all -n argocd
    - name: access ArgoCD
      uses: nick-fields/retry@v2
      with: 
        max_attempts: 300
        retry_on: error
        timeout_minutes: 5
        command: |
          kubectl port-forward svc/argocd-server -n argocd 8080:443